services:
  backend:
    restart: "unless-stopped"
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    depends_on:
      - db
    environment:
      - DB_HOST=db
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]

  db:
    image: docker.io/postgres:alpine
    restart: "unless-stopped"
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRES_USER=picture_shop
      - POSTGRES_PASSWORD=picture_shop
      - POSTGRES_DB=picture_shop
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=ru_RU.UTF-8 --lc-ctype=ru_RU.UTF-8
    volumes:
      - ./.schemas:/var/lib/postgresql/data

  redis:
    image: redis:latest
    volumes:
      - ./.redis_data:/data
    command: redis-server --dir /data
    ports:
      - "6379:6379/tcp"
    restart: "unless-stopped"