# Generated by Django 5.1.1 on 2024-09-24 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_orderitem_orderpainting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpainting',
            name='quantity',
        ),
    ]
